window.COLDEM_SEED = {
  "generatedAt": "2026-07-23T14:30:00-06:00",
  "dataset": {
    "totalLeads": 310,
    "statusCounts": {
      "Lost": 100,
      "Contactado": 124,
      "Qualified": 35,
      "Tour Agendado": 6,
      "Inscrito": 19,
      "Pasadía Agendado": 2,
      "Sin estatus": 5,
      "En Proceso": 1,
      "Tour Realizado": 4,
      "Lead Nuevo": 14
    },
    "advisorCounts": {
      "Sin asignar": 127,
      "Patty": 136,
      "Cinthia": 22,
      "Lucía": 25
    },
    "funnel": {
      "Leads": 310,
      "Contactados": 274,
      "Respondieron": 223,
      "Qualified": 48,
      "Tour agendado": 43,
      "Tour atendido": 34,
      "Pasadía agendada": 23,
      "Pasadía atendida": 19,
      "Retroalimentación": 14,
      "Inscritos": 19
    },
    "sources": [
      {
        "source": "Facebook",
        "leads": 240,
        "qualified": 34,
        "tourBooked": 20,
        "tourAttended": 13,
        "enrolled": 3
      },
      {
        "source": "Google",
        "leads": 3,
        "qualified": 1,
        "tourBooked": 1,
        "tourAttended": 1,
        "enrolled": 0
      },
      {
        "source": "Instagram",
        "leads": 24,
        "qualified": 3,
        "tourBooked": 3,
        "tourAttended": 2,
        "enrolled": 1
      },
      {
        "source": "Referido",
        "leads": 14,
        "qualified": 6,
        "tourBooked": 13,
        "tourAttended": 12,
        "enrolled": 9
      },
      {
        "source": "Sin fuente",
        "leads": 21,
        "qualified": 3,
        "tourBooked": 0,
        "tourAttended": 0,
        "enrolled": 0
      },
      {
        "source": "Walk In",
        "leads": 8,
        "qualified": 1,
        "tourBooked": 6,
        "tourAttended": 6,
        "enrolled": 6
      }
    ],
    "lostReasons": [
      {
        "reason": "Otro",
        "count": 32
      },
      {
        "reason": "No se cuenta con el nivel",
        "count": 21
      },
      {
        "reason": "Distancia",
        "count": 16
      },
      {
        "reason": "No contesta",
        "count": 13
      },
      {
        "reason": "Precio",
        "count": 6
      },
      {
        "reason": "Otro colegio",
        "count": 6
      },
      {
        "reason": "Sin motivo",
        "count": 2
      },
      {
        "reason": "Horarios",
        "count": 2
      },
      {
        "reason": "Ciclo futuro",
        "count": 1
      },
      {
        "reason": "Transporte",
        "count": 1
      }
    ],
    "activeLeads": [
      {
        "id": "L260125",
        "family": "Familia 125",
        "student": "Alumno",
        "level": "SECUNDARIA",
        "grade": "Sin grado",
        "source": "Sin fuente",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "6/23/2026",
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260135",
        "family": "Familia 135",
        "student": "Alumno",
        "level": "Prepa",
        "grade": 1,
        "source": "Sin fuente",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 1,
        "lastInteraction": "6/23/2026",
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260156",
        "family": "Familia 156",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "1° Secundaria",
        "source": "Facebook",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "6/25/2026",
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260158",
        "family": "Familia 158",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "Sin grado",
        "source": "Instagram",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 1,
        "lastInteraction": "6/24/2026",
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260167",
        "family": "Familia 167",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "1° Primaria",
        "source": "Sin fuente",
        "owner": "Lucía",
        "status": "Lead Nuevo",
        "calls": 0,
        "lastInteraction": "6/25/2026",
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Enviar preguntas de calificación"
      },
      {
        "id": "L260273",
        "family": "Familia 273",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "3° Primaria",
        "source": "Facebook",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 3,
        "lastInteraction": 46218,
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260296",
        "family": "Familia 296",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Referido",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": 46225,
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260299",
        "family": "Familia 299",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": 46225,
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260303",
        "family": "Familia 303",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Patty",
        "status": "Lead Nuevo",
        "calls": 0,
        "lastInteraction": 46226,
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Enviar preguntas de calificación"
      },
      {
        "id": "L260304",
        "family": "Familia 304",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Patty",
        "status": "Lead Nuevo",
        "calls": 0,
        "lastInteraction": 46226,
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Enviar preguntas de calificación"
      },
      {
        "id": "L260306",
        "family": "Familia 306",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Sin fuente",
        "owner": "Patty",
        "status": "Qualified",
        "calls": 0,
        "lastInteraction": 46226,
        "daysStuck": 999,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260004",
        "family": "Familia 004",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-10",
        "daysStuck": 43,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260006",
        "family": "Familia 006",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "1° Secundaria",
        "source": "Walk In",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-10",
        "daysStuck": 43,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260257",
        "family": "Familia 257",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "5° Primaria",
        "source": "Facebook",
        "owner": "Lucía",
        "status": "Qualified",
        "calls": 8,
        "lastInteraction": "2026-06-11",
        "daysStuck": 42,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260008",
        "family": "Familia 008",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "1° Secundaria",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Tour Agendado",
        "calls": 0,
        "lastInteraction": "2026-06-15",
        "daysStuck": 38,
        "priority": "Alta",
        "nextAction": "Reagendar no-show"
      },
      {
        "id": "L260038",
        "family": "Familia 038",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260069",
        "family": "Familia 069",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260070",
        "family": "Familia 070",
        "student": "Alumno",
        "level": "SECUNDARIA",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260071",
        "family": "Familia 071",
        "student": "Alumno",
        "level": "PRIMARIA",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260085",
        "family": "Familia 085",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260086",
        "family": "Familia 086",
        "student": "Alumno",
        "level": "Primaria-Secundaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260087",
        "family": "Familia 087",
        "student": "Alumno",
        "level": "PRIMARIA",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260089",
        "family": "Familia 089",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Sin fuente",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 1,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 2/5 + WhatsApp"
      },
      {
        "id": "L260090",
        "family": "Familia 090",
        "student": "Alumno",
        "level": "Prepa",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260091",
        "family": "Familia 091",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260093",
        "family": "Familia 093",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 1,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260095",
        "family": "Familia 095",
        "student": "Alumno",
        "level": "Primaria-Secundaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 0,
        "lastInteraction": "2026-06-16",
        "daysStuck": 37,
        "priority": "Alta",
        "nextAction": "Llamada 1/5 + WhatsApp"
      },
      {
        "id": "L260009",
        "family": "Familia 009",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "3° Primaria",
        "source": "Walk In",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260010",
        "family": "Familia 010",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "2° Primaria",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260012",
        "family": "Familia 012",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "3° Primaria",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260015",
        "family": "Familia 015",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260016",
        "family": "Familia 016",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260017",
        "family": "Familia 017",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 1,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260018",
        "family": "Familia 018",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260020",
        "family": "Familia 020",
        "student": "Alumno",
        "level": "Prepa",
        "grade": "1° Prepa",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 3,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260021",
        "family": "Familia 021",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 0,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 1/5 + WhatsApp"
      },
      {
        "id": "L260023",
        "family": "Familia 023",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Instagram",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260029",
        "family": "Familia 029",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260030",
        "family": "Familia 030",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260031",
        "family": "Familia 031",
        "student": "Alumno",
        "level": "Prepa",
        "grade": "1° Prepa",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260032",
        "family": "Familia 032",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 1,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260033",
        "family": "Familia 033",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Instagram",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260034",
        "family": "Familia 034",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260037",
        "family": "Familia 037",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260039",
        "family": "Familia 039",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "1° Secundaria",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260040",
        "family": "Familia 040",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260041",
        "family": "Familia 041",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260044",
        "family": "Familia 044",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260045",
        "family": "Familia 045",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260046",
        "family": "Familia 046",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260048",
        "family": "Familia 048",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260050",
        "family": "Familia 050",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260051",
        "family": "Familia 051",
        "student": "Alumno",
        "level": "Secundaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260053",
        "family": "Familia 053",
        "student": "Alumno",
        "level": "Primaria",
        "grade": "4° Primaria",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260054",
        "family": "Familia 054",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260055",
        "family": "Familia 055",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260057",
        "family": "Familia 057",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260060",
        "family": "Familia 060",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Sin fuente",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      },
      {
        "id": "L260061",
        "family": "Familia 061",
        "student": "Alumno",
        "level": "Primaria-Secundaria",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Qualified",
        "calls": 1,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Agendar School Tour"
      },
      {
        "id": "L260062",
        "family": "Familia 062",
        "student": "Alumno",
        "level": "Sin nivel",
        "grade": "Sin grado",
        "source": "Facebook",
        "owner": "Sin asignar",
        "status": "Contactado",
        "calls": 2,
        "lastInteraction": "2026-06-17",
        "daysStuck": 36,
        "priority": "Alta",
        "nextAction": "Llamada 3/5 + WhatsApp"
      }
    ],
    "missingCounts": {
      "Sin asesor": 127,
      "Sin nivel": 175,
      "Sin grado": 239,
      "Sin estatus": 5,
      "Sin fuente": 21
    }
  },
  "dailyHistory": [
    {
      "id": "seed-1",
      "date": "2026-01-22",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-2",
      "date": "2026-01-27",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-3",
      "date": "2026-01-28",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 2,
      "passDayAttended": 2,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-4",
      "date": "2026-01-29",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 2,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 1,
      "enrolled": 2,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-5",
      "date": "2026-03-05",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-6",
      "date": "2026-03-23",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-7",
      "date": "2026-04-24",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-8",
      "date": "2026-05-14",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 2,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 2,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-9",
      "date": "2026-05-29",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-10",
      "date": "2026-06-01",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 2,
      "passDayAttended": 2,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-11",
      "date": "2026-06-02",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-12",
      "date": "2026-06-03",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 2,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-13",
      "date": "2026-06-04",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-14",
      "date": "2026-06-05",
      "owner": "Equipo",
      "paidLeads": 3,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 1,
      "qualified": 2,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-15",
      "date": "2026-06-06",
      "owner": "Equipo",
      "paidLeads": 8,
      "organicLeads": 2,
      "contactWhatsApp": 6,
      "calls": 0,
      "responses": 1,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-16",
      "date": "2026-06-07",
      "owner": "Equipo",
      "paidLeads": 13,
      "organicLeads": 1,
      "contactWhatsApp": 4,
      "calls": 0,
      "responses": 1,
      "qualified": 2,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-17",
      "date": "2026-06-08",
      "owner": "Equipo",
      "paidLeads": 14,
      "organicLeads": 0,
      "contactWhatsApp": 7,
      "calls": 0,
      "responses": 13,
      "qualified": 3,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-18",
      "date": "2026-06-09",
      "owner": "Equipo",
      "paidLeads": 9,
      "organicLeads": 2,
      "contactWhatsApp": 7,
      "calls": 0,
      "responses": 14,
      "qualified": 3,
      "noQualified": 0,
      "tourBooked": 2,
      "tourAttended": 2,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 2,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-19",
      "date": "2026-06-10",
      "owner": "Equipo",
      "paidLeads": 8,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 1,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 2,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-20",
      "date": "2026-06-11",
      "owner": "Equipo",
      "paidLeads": 7,
      "organicLeads": 1,
      "contactWhatsApp": 15,
      "calls": 0,
      "responses": 14,
      "qualified": 4,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-21",
      "date": "2026-06-12",
      "owner": "Equipo",
      "paidLeads": 9,
      "organicLeads": 0,
      "contactWhatsApp": 20,
      "calls": 0,
      "responses": 17,
      "qualified": 4,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 1,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-22",
      "date": "2026-06-13",
      "owner": "Equipo",
      "paidLeads": 15,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-23",
      "date": "2026-06-14",
      "owner": "Equipo",
      "paidLeads": 2,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-24",
      "date": "2026-06-15",
      "owner": "Equipo",
      "paidLeads": 9,
      "organicLeads": 0,
      "contactWhatsApp": 20,
      "calls": 0,
      "responses": 25,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 0,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 1,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-25",
      "date": "2026-06-16",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 15,
      "calls": 0,
      "responses": 11,
      "qualified": 3,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 2,
      "passDayAttended": 2,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-26",
      "date": "2026-06-17",
      "owner": "Equipo",
      "paidLeads": 5,
      "organicLeads": 0,
      "contactWhatsApp": 6,
      "calls": 0,
      "responses": 6,
      "qualified": 3,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 1,
      "passDayAttended": 0,
      "feedbacks": 2,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-27",
      "date": "2026-06-18",
      "owner": "Equipo",
      "paidLeads": 10,
      "organicLeads": 0,
      "contactWhatsApp": 10,
      "calls": 0,
      "responses": 10,
      "qualified": 3,
      "noQualified": 0,
      "tourBooked": 4,
      "tourAttended": 3,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-28",
      "date": "2026-06-19",
      "owner": "Equipo",
      "paidLeads": 5,
      "organicLeads": 0,
      "contactWhatsApp": 4,
      "calls": 0,
      "responses": 4,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 2,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-29",
      "date": "2026-06-20",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 1,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-30",
      "date": "2026-06-21",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-31",
      "date": "2026-06-22",
      "owner": "Equipo",
      "paidLeads": 12,
      "organicLeads": 1,
      "contactWhatsApp": 13,
      "calls": 0,
      "responses": 13,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 2,
      "tourAttended": 2,
      "passDayBooked": 1,
      "passDayAttended": 1,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-32",
      "date": "2026-06-23",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 9,
      "calls": 0,
      "responses": 9,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 1,
      "passDayAttended": 0,
      "feedbacks": 2,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-33",
      "date": "2026-06-24",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-34",
      "date": "2026-06-25",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 2,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-35",
      "date": "2026-06-26",
      "owner": "Equipo",
      "paidLeads": 3,
      "organicLeads": 0,
      "contactWhatsApp": 2,
      "calls": 0,
      "responses": 3,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-36",
      "date": "2026-06-27",
      "owner": "Equipo",
      "paidLeads": 1,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-37",
      "date": "2026-06-28",
      "owner": "Equipo",
      "paidLeads": 1,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-38",
      "date": "2026-06-29",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 4,
      "calls": 0,
      "responses": 1,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-39",
      "date": "2026-06-30",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 2,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-40",
      "date": "2026-07-01",
      "owner": "Equipo",
      "paidLeads": 5,
      "organicLeads": 0,
      "contactWhatsApp": 3,
      "calls": 0,
      "responses": 3,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-41",
      "date": "2026-07-02",
      "owner": "Equipo",
      "paidLeads": 14,
      "organicLeads": 0,
      "contactWhatsApp": 16,
      "calls": 0,
      "responses": 11,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-42",
      "date": "2026-07-03",
      "owner": "Equipo",
      "paidLeads": 8,
      "organicLeads": 0,
      "contactWhatsApp": 7,
      "calls": 0,
      "responses": 6,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-43",
      "date": "2026-07-04",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-44",
      "date": "2026-07-05",
      "owner": "Equipo",
      "paidLeads": 2,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-45",
      "date": "2026-07-06",
      "owner": "Equipo",
      "paidLeads": 6,
      "organicLeads": 0,
      "contactWhatsApp": 11,
      "calls": 9,
      "responses": 5,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-46",
      "date": "2026-07-07",
      "owner": "Equipo",
      "paidLeads": 1,
      "organicLeads": 0,
      "contactWhatsApp": 1,
      "calls": 14,
      "responses": 0,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-47",
      "date": "2026-07-08",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 5,
      "calls": 10,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-48",
      "date": "2026-07-09",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 5,
      "calls": 17,
      "responses": 10,
      "qualified": 4,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-49",
      "date": "2026-07-10",
      "owner": "Equipo",
      "paidLeads": 8,
      "organicLeads": 1,
      "contactWhatsApp": 9,
      "calls": 15,
      "responses": 3,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 2,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-50",
      "date": "2026-07-11",
      "owner": "Equipo",
      "paidLeads": 2,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-51",
      "date": "2026-07-12",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-52",
      "date": "2026-07-13",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 1,
      "contactWhatsApp": 4,
      "calls": 10,
      "responses": 2,
      "qualified": 2,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-53",
      "date": "2026-07-14",
      "owner": "Equipo",
      "paidLeads": 9,
      "organicLeads": 0,
      "contactWhatsApp": 7,
      "calls": 16,
      "responses": 1,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-54",
      "date": "2026-07-15",
      "owner": "Equipo",
      "paidLeads": 3,
      "organicLeads": 0,
      "contactWhatsApp": 6,
      "calls": 19,
      "responses": 0,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-55",
      "date": "2026-07-16",
      "owner": "Equipo",
      "paidLeads": 4,
      "organicLeads": 0,
      "contactWhatsApp": 4,
      "calls": 13,
      "responses": 2,
      "qualified": 2,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-56",
      "date": "2026-07-17",
      "owner": "Equipo",
      "paidLeads": 5,
      "organicLeads": 0,
      "contactWhatsApp": 4,
      "calls": 8,
      "responses": 1,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-57",
      "date": "2026-07-18",
      "owner": "Equipo",
      "paidLeads": 5,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-58",
      "date": "2026-07-19",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 0,
      "contactWhatsApp": 0,
      "calls": 0,
      "responses": 0,
      "qualified": 0,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-59",
      "date": "2026-07-20",
      "owner": "Equipo",
      "paidLeads": 0,
      "organicLeads": 1,
      "contactWhatsApp": 7,
      "calls": 0,
      "responses": 0,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 1,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-60",
      "date": "2026-07-21",
      "owner": "Equipo",
      "paidLeads": 5,
      "organicLeads": 0,
      "contactWhatsApp": 5,
      "calls": 0,
      "responses": 0,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 2,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 1,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-61",
      "date": "2026-07-22",
      "owner": "Equipo",
      "paidLeads": 7,
      "organicLeads": 1,
      "contactWhatsApp": 6,
      "calls": 15,
      "responses": 0,
      "qualified": 2,
      "noQualified": 0,
      "tourBooked": 0,
      "tourAttended": 0,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    },
    {
      "id": "seed-62",
      "date": "2026-07-23",
      "owner": "Equipo",
      "paidLeads": 1,
      "organicLeads": 0,
      "contactWhatsApp": 4,
      "calls": 0,
      "responses": 0,
      "qualified": 1,
      "noQualified": 0,
      "tourBooked": 2,
      "tourAttended": 1,
      "passDayBooked": 0,
      "passDayAttended": 0,
      "feedbacks": 0,
      "enrolled": 0,
      "pendingEnd": 0,
      "weekendBacklogStart": 0,
      "notes": "",
      "source": "Excel histórico",
      "isSeed": true
    }
  ]
};
